import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import { Header } from "./Header";
>>>>>>> 57d96f4f333df62b16a424aa1558667f6f21eecc

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
<<<<<<< HEAD
      <body>{children}</body>
=======
      <body>
        {children}
        {/* <hr /> */}
        {/* <br /> */}
        <Header />
      </body>
>>>>>>> 57d96f4f333df62b16a424aa1558667f6f21eecc
    </html>
  );
}
